---
# ─────────────────────────────────────────
# СИСТЕМНЫЕ УТИЛИТЫ
# ─────────────────────────────────────────

- name: Обновить apt-кэш
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Установить базовые системные утилиты
  apt:
    name:
      - curl
      - git
      - make
      - mc            # Midnight Commander — файловый менеджер
      - btop          # Современный мониторинг процессов
      - brightnessctl # Управление яркостью экрана
      - expect        # Автоматизация интерактивных команд
      - openconnect   # VPN-клиент (Cisco AnyConnect совместимый)
    state: present